services:
  llama_cpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama_cpp
    ports:
      - "8000:8000"
    volumes:
      - ./quenmodel:/models:ro
    command: |
      -m /models/Qwen3.5-2B-Q8_0.gguf
      --host 0.0.0.0
      --port 8000
      --n-gpu-layers 99